language: generic
sudo: required

services:
  - docker


before_install:
  - docker build -t sofisticat/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sofisticat/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "testing-docker-travis"
  env: "Testingdockertravis"
  bucket_name: "elasticbeanstalk-us-west-2-534862895681"
  bucket_path: "testing-docker-travis"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY



