sudo: required

services:
  - docker


before_install:
  - docker build -t sofisticat/docker-react -f Dockerfile.dev .

script:
  - docker run sofisticat/docker-react npm run test -- --coverage CI=true